[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/booking"
  to = "/booking.html"
  status = 200

[[redirects]]
  from = "/admin-login"
  to = "/admin-login.html"
  status = 200

[[redirects]]
  from = "/admin-dashboard"
  to = "/admin-dashboard.html"
  status = 200

[[redirects]]
  from = "/user-dashboard"
  to = "/user-dashboard.html"
  status = 200
