#!/usr/bin/env bash
# TEAM MRC - Gallery Setup & Test Script

echo "🚀 TEAM MRC - Interactive Gallery Setup"
echo "======================================"
echo ""

# Check Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Node.js is not installed. Please install Node.js 16+"
    exit 1
fi

echo "✅ Node.js version: $(node -v)"
echo ""

# Install dependencies
echo "📦 Installing dependencies..."
npm install

echo ""
echo "✅ Dependencies installed!"
echo ""

# Display available commands
echo "📋 Available Commands:"
echo ""
echo "Development:"
echo "  npm run dev              - Start development server (http://localhost:3000)"
echo "  npm run preview          - Preview production build"
echo ""
echo "Testing:"
echo "  npm test                 - Run unit tests (watch mode)"
echo "  npm test:once           - Run unit tests (single run)"
echo "  npm test:coverage       - Generate coverage report"
echo "  npm run test:e2e        - Run E2E tests"
echo ""
echo "Build & Deploy:"
echo "  npm run build           - Create production build"
echo "  npm run lint            - Lint and fix code"
echo "  npm run format          - Format code with Prettier"
echo ""
echo "Analysis:"
echo "  npm audit              - Check for vulnerabilities"
echo "  npm run lighthouse     - Run Lighthouse audit"
echo ""
echo "======================================"
echo "🎯 Quick Start:"
echo ""
echo "1. Start dev server:"
echo "   npm run dev"
echo ""
echo "2. Open browser:"
echo "   http://localhost:3000"
echo ""
echo "3. Try these interactions:"
echo "   • Hover over gallery cards (see descriptions)"
echo "   • Click cards to open modal"
echo "   • Use arrow keys to navigate"
echo "   • Press Escape to close"
echo "   • Toggle dark/light theme"
echo "   • Test on mobile (responsive design)"
echo ""
echo "4. Run tests:"
echo "   npm test"
echo ""
echo "======================================"
echo "📸 Gallery Features:"
echo ""
echo "✅ Bus Gallery - 5 items (3 images + 2 videos)"
echo "✅ Van Gallery - 5 items (all images)"
echo "✅ Car Gallery - 2 items (image + video)"
echo "✅ Media Gallery - 3 items (all videos)"
echo ""
echo "✅ Interactive Features:"
echo "   • Card hover descriptions"
echo "   • Auto-advancing slider (10s)"
echo "   • Keyboard navigation"
echo "   • Mobile responsive"
echo "   • Dark/light theme"
echo "   • Accessibility (WCAG AA)"
echo ""
echo "======================================"
echo "✨ Ready to go! Start with: npm run dev"
echo ""
